data1 = read.csv('S5_A_data', sep = '\t', header = FALSE)
data2 = read.csv('S5_B_data', sep = '\t', header = FALSE)
data3 = read.csv('S5_C_data', sep = '\t', header = FALSE)
data4 = read.csv('S5_D_data', sep = '\t', header = FALSE)
residues = readLines('S5_rownames')

setEPS()
postscript("S5_curvature.eps")
boxplot(data1,col="red",ylim=c(0,100),xaxt = 'n')
par(new=TRUE)
boxplot(data2,col="blue",ylim=c(0,100),xaxt = 'n')
par(new=TRUE)
boxplot(data3,col="green",ylim=c(0,100),labRow = residues,xaxt = 'n')
par(new=TRUE)
boxplot(data4,col="yellow",ylim=c(0,100),xlab="Residue Number",ylab="Curvature",main="Helicity of S5 Helix",xaxt = 'n')
text(x =  seq_along(residues), y = par("usr")[3] - 1, srt = 90, adj = 1, labels = residues, xpd = TRUE)
legend(32.5, 101, c("A Chain","B Chain","C Chain","D Chain"),col=c("red","blue","green","yellow"),lty=c(1,1),lwd=c(2.5,2.5))
dev.off()


plot.new()
frame()

setEPS()
postscript("heatmap_S5_A.eps")
datamatrix <-as.matrix(data1,headers = FALSE)
cc <- rainbow(ncol(datamatrix), start = 0, end = 0.5)
frames <- rep("", nrow(datamatrix))
frames[seq(1,nrow(datamatrix), 100)] <- seq(1, nrow(datamatrix), 100)
heatmap(datamatrix,Rowv = NA, Colv = NA, scale = "row",xlab = "S5 Helix Residue", ylab =  "Time",col = cc, ColSideColors = cc,labCol = residues,labRow = frames, cexRow=2,cexCol=1)
dev.off()

plot.new()
frame()

setEPS()
postscript("heatmap_S5_B.eps")
datamatrix <-as.matrix(data2,headers = FALSE)
cc <- rainbow(ncol(datamatrix), start = 0, end = 0.5)
frames <- rep("", nrow(datamatrix))
frames[seq(1,nrow(datamatrix), 100)] <- seq(1, nrow(datamatrix), 100)
heatmap(datamatrix,Rowv = NA, Colv = NA, scale = "row",xlab = "S5 Helix Residue", ylab =  "Time",col = cc, ColSideColors = cc,labCol = residues,labRow = frames, cexRow=2,cexCol=1)
dev.off()

plot.new()
frame()

setEPS()
postscript("heatmap_S5_C.eps")
datamatrix <-as.matrix(data3,headers = FALSE)
cc <- rainbow(ncol(datamatrix), start = 0, end = 0.5)
frames <- rep("", nrow(datamatrix))
frames[seq(1,nrow(datamatrix), 100)] <- seq(1, nrow(datamatrix), 100)
heatmap(datamatrix,Rowv = NA, Colv = NA, scale = "row",xlab = "S5 Helix Residue", ylab =  "Time",col = cc, ColSideColors = cc,labCol = residues,labRow = frames, cexRow=2,cexCol=1)
dev.off()

plot.new()
frame()

setEPS()
postscript("heatmap_S5_D.eps")
datamatrix <-as.matrix(data4,headers = FALSE)
cc <- rainbow(ncol(datamatrix), start = 0, end = 0.5)
frames <- rep("", nrow(datamatrix))
frames[seq(1,nrow(datamatrix), 100)] <- seq(1, nrow(datamatrix), 100)
heatmap(datamatrix,Rowv = NA, Colv = NA, scale = "row",xlab = "S5 Helix Residue", ylab =  "Time",col = cc, ColSideColors = cc,labCol = residues,labRow = frames, cexRow=2,cexCol=1)
dev.off()

